Add Python module (#5)
* Move imports, modules, and python directories

Move those directories into the share directory will keep clean the
project's root directory.

* Add a python module to handle the future releases

This python module will allow to install several versions of this project -
starting with the **future** (may be 1.1.0 or 2.0.0) release - in order to
have a better handling in the projects using Stòiridh Qbs Tools.

From now on Python is not optional anymore!

* Add Continuous Integration support

This update will allow to test the Python API.

* Quickly fix for the testing section.

Indeed, 'py' is only available for Windows.

* Fix an issue while trying to open an archive file

The error in the CI log was Python raises the following exception:

AttributeError: module 'lzma' has no attribute 'LZMAFile'

So as to get round this issue, I added explicitly the gzip mode in order to
open the archive because it ends with the '.tar.gz' file extension and not
the '.tar.xz' file extension.