Fix an issue while trying to open an archive file
The error in the CI log was Python raises the following exception:

AttributeError: module 'lzma' has no attribute 'LZMAFile'

So as to get round this issue, I added explicitly the gzip mode in order to
open the archive because it ends with the '.tar.gz' file extension and not
the '.tar.xz' file extension.